FROM kubeflownotebookswg/jupyter-scipy:v1.8.0-rc.1

USER root
# update - ensure apt packages are always updated
RUN export DEBIAN_FRONTEND=noninteractive && \
  apt-get clean all && \
     apt-get update && \
     apt-get upgrade -y && \
     apt-get install -y  \
         autoconf \
         build-essential \
         cmake \
         git \
         libbz2-dev \
         libcurl4-openssl-dev \
         libssl-dev \
         zlib1g-dev \
         liblzma-dev

  # apt clean and remove cached source lists
 RUN apt-get clean && \
     rm -rf /var/lib/apt/lists/*

 RUN git clone https://github.com/samtools/htslib.git
 RUN cd htslib && \
     git submodule update --init --recursive && \
     autoheader && \
     autoconf && \
     ./configure --prefix=/usr/local/ && \
     make && \
     make install
  
# Install popscle
 RUN git clone https://github.com/statgen/popscle.git
 RUN cd popscle && \
     mkdir build && \
     cd build && \
     cmake .. && \
     make
 RUN cp /popscle/bin/popscle /usr/local/bin
USER $NB_UID
RUN pip install scanpy pandas numpy scipy seaborn scikit-learn matplotlib boto3 awscli

  # Define default command
 #CMD ["popscle"]
# you may want to look at that shell script
#COPY ./entrypoint.sh /
# RUN chmod 755 /entrypoint.sh
# ENTRYPOINT ["/entrypoint.sh"]
