FROM tmatteso/ye-lab-ucsf:python3.7

USER root
# update - ensure apt packages are always updated
#RUN export DEBIAN_FRONTEND=noninteractive \
RUN apt-get -yq update 
# && apt-get -yq upgrade \
#RUN apt-get install build-essential -yq 
RUN apt-get clean &&  rm -rf /var/lib/apt/lists/*

# add desired package -- these should be version controlled eventually, and need a requirements.txt
RUN pip install scikit-learn==0.20.3
RUN pip install Biopython==1.73
RUN pip install pandas matplotlib boto3 awscli
#RUN pip install scanpy scikit-learn matplotlib boto3 awscli muon anndata torch
USER $NB_UID
