# start with base image with torch and cuda drivers
#FROM public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-pytorch-cuda-full:v1.5.0
#FROM public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-pytorch-cuda:v1.5.0
FROM public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-scipy:v1.5.0

USER root
# update - ensure apt packages are always updated
RUN export DEBIAN_FRONTEND=noninteractive \
 && apt-get -yq update \
 && apt-get -yq upgrade \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# add desired package -- these should be version controlled eventually, and need a requirements.txt
RUN pip install scanpy pandas numpy scipy seaborn scikit-learn matplotlib boto3 awscli

USER $NB_UID
#RUN cd .. 
# ensure image passes CI tests (Github Actions)

