# start with base image with torch and cuda drivers
#FROM public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-pytorch-cuda-full:v1.5.0
#FROM public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-pytorch-cuda:v1.5.0
#FROM public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-pytorch-cuda:v1.5.0
#FROM public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-scipy:v1.5.0
# this new base image makes it much harder to replace python with 3.6
# the old base images above are no longer on ecr. we can only use my custom images as a base. yikes!
#FROM public.ecr.aws/kubeflow-on-aws/notebook-servers/jupyter-pytorch:2.0.0-gpu-py310-cu118-ubuntu20.04-ec2-v1.0
# sc is a bad one to start with, has no cuda drivers
FROM tmatteso/ye-lab-ucsf:scvi

USER root
# update - ensure apt packages are always updated
#RUN export DEBIAN_FRONTEND=noninteractive \
RUN apt-get -yq update 
# && apt-get -yq upgrade \
RUN apt-get install build-essential -yq 
# && apt-get install -yq bash #\
RUN apt-get clean &&  rm -rf /var/lib/apt/lists/*

RUN conda install python=3.6 -yq
RUN conda config --add channels defaults
RUN conda config --add channels conda-forge
RUN conda config --add channels bioconda

# add desired package -- these should be version controlled eventually, and need a requirements.txt
RUN conda install bedops
RUN pip install scanpy scikit-learn matplotlib boto3 awscli muon anndata torch
RUN pip install h5py>=2.7.0 pandas==0.22.0 scipy>=0.19.1 numpy>=1.14.2 six>=1.11.0 pyfasta>=0.5.2 xgboost==0.7.post4
#RUN pip install scanpy scikit-learn matplotlib boto3 awscli muon anndata torch

USER $NB_UID
# let's see if the repo works from here
#WORKDIR /home/jovyan
#RUN git clone https://github.com/FunctionLab/ExPecto.git \
# && cd ExPecto #\
# && sh download_resources.sh; tar xf resources_20190807.tar.gz \
#RUN cd .. 
# ensure image passes CI tests (Github Actions)
